/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    mediaFolders: MediaFolder;
    media: Media;
    pages: Page;
    productSeries: ProductSery;
    products: Product;
    faq: Faq;
    caseStudies: CaseStudy;
    tickets: Ticket;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    mediaFolders: MediaFoldersSelect<false> | MediaFoldersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    productSeries: ProductSeriesSelect<false> | ProductSeriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh' | 'en' | 'ja') | ('zh' | 'en' | 'ja')[];
  globals: {
    siteSettings: SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'zh' | 'en' | 'ja';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaFolders".
 */
export interface MediaFolder {
  id: number;
  name: string;
  slug: string;
  parent?: (number | null) | MediaFolder;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Used to categorize media items (supports parent/child folders).
   */
  folder?: (number | null) | MediaFolder;
  sourcePath?: string | null;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  intro?: {
    title?: string | null;
    description?: string | null;
  };
  blocks: (
    | {
        autoPlayInterval?: number | null;
        slides: {
          slideId: number;
          media: number | Media;
          alt?: string | null;
          action?: {
            href?: string | null;
            label?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title?: string | null;
        paragraph?: string | null;
        featuredProducts?: {
          title?: string | null;
          description?: string | null;
          ctaDescription?: string | null;
          viewAllLabel?: string | null;
          slugs?: (number | Product)[] | null;
        };
        highlights: {
          title: string;
          description?: string | null;
          link?: string | null;
          tags?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        /**
         * Optional: drag to reorder series; if empty, series uses its default order.
         */
        seriesOrder?:
          | {
              series: number | ProductSery;
              id?: string | null;
            }[]
          | null;
        /**
         * Drag to reorder product cards. Unlisted products will be appended to the end automatically.
         */
        productOrder?:
          | {
              product: number | Product;
              id?: string | null;
            }[]
          | null;
        coreTitle: string;
        coreDescription: string;
        viewDetailsCta: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productsCatalog';
      }
    | {
        title?: string | null;
        description?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        items?:
          | {
              title: string;
              paragraph?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'about';
      }
    | {
        category: 'practical-teaching' | 'sci-tech-innovation' | 'innovation-competition' | 'training-base';
        /**
         * Maximum number of items to display (default 50).
         */
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudiesList';
      }
    | {
        title?: string | null;
        description?: string | null;
        form?: {
          nameLabel?: string | null;
          namePlaceholder?: string | null;
          emailLabel?: string | null;
          emailPlaceholder?: string | null;
          phoneLabel?: string | null;
          phonePlaceholder?: string | null;
          intentionLabel?: string | null;
          intentionPlaceholder?: string | null;
          intentionOptions?:
            | {
                option?: string | null;
                id?: string | null;
              }[]
            | null;
          messageLabel?: string | null;
          messagePlaceholder?: string | null;
          submitLabel?: string | null;
          submitSuccessMessage?: string | null;
          submitErrorMessage?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        title?: string | null;
        images: {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageGallery';
      }
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  model?: string | null;
  series?: (number | null) | ProductSery;
  heroImage?: (number | null) | Media;
  brief?: string | null;
  details?: {
    subtitle?: string | null;
    overview?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    applicable?: string | null;
    features?:
      | {
          title: string;
          content?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          image?: (number | null) | Media;
          gallery?:
            | {
                name?: string | null;
                image?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    sampleCases?: {
      title?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      sections?:
        | {
            title?: string | null;
            items?:
              | {
                  name?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
    sensorConfig?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    controllerConfig?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    softwareConfig?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    experiments?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productSeries".
 */
export interface ProductSery {
  id: number;
  key: string;
  title: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  product?: (number | Product)[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  category: 'practical-teaching' | 'sci-tech-innovation' | 'innovation-competition' | 'training-base';
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  name: string;
  email?: string | null;
  phone: string;
  intention: string;
  message?: string | null;
  status?: ('pending' | 'in_progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'mediaFolders';
        value: number | MediaFolder;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'productSeries';
        value: number | ProductSery;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaFolders_select".
 */
export interface MediaFoldersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  folder?: T;
  sourcePath?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?:
    | T
    | {
        title?: T;
        description?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              autoPlayInterval?: T;
              slides?:
                | T
                | {
                    slideId?: T;
                    media?: T;
                    alt?: T;
                    action?:
                      | T
                      | {
                          href?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              paragraph?: T;
              featuredProducts?:
                | T
                | {
                    title?: T;
                    description?: T;
                    ctaDescription?: T;
                    viewAllLabel?: T;
                    slugs?: T;
                  };
              highlights?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?: T;
                    tags?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productsCatalog?:
          | T
          | {
              seriesOrder?:
                | T
                | {
                    series?: T;
                    id?: T;
                  };
              productOrder?:
                | T
                | {
                    product?: T;
                    id?: T;
                  };
              coreTitle?: T;
              coreDescription?: T;
              viewDetailsCta?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              content?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              imageAlt?: T;
              items?:
                | T
                | {
                    title?: T;
                    paragraph?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseStudiesList?:
          | T
          | {
              category?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
              form?:
                | T
                | {
                    nameLabel?: T;
                    namePlaceholder?: T;
                    emailLabel?: T;
                    emailPlaceholder?: T;
                    phoneLabel?: T;
                    phonePlaceholder?: T;
                    intentionLabel?: T;
                    intentionPlaceholder?: T;
                    intentionOptions?:
                      | T
                      | {
                          option?: T;
                          id?: T;
                        };
                    messageLabel?: T;
                    messagePlaceholder?: T;
                    submitLabel?: T;
                    submitSuccessMessage?: T;
                    submitErrorMessage?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productSeries_select".
 */
export interface ProductSeriesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  model?: T;
  series?: T;
  heroImage?: T;
  brief?: T;
  details?:
    | T
    | {
        subtitle?: T;
        overview?: T;
        applicable?: T;
        features?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              gallery?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        sampleCases?:
          | T
          | {
              title?: T;
              description?: T;
              sections?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          name?: T;
                          image?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        sensorConfig?: T;
        controllerConfig?: T;
        softwareConfig?: T;
        experiments?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  product?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  intention?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  /**
   * Brand logos used by the website frontend header and footer. Configure light and dark mode variants separately.
   */
  frontendBranding?: {
    headerLogo?: (number | null) | Media;
    headerLogoInverse?: (number | null) | Media;
    footerLogo?: (number | null) | Media;
    footerLogoInverse?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  /**
   * Legacy field: footer contact info has moved to the Footer global. Edit it under Pages & Layout -> Footer.
   */
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  /**
   * Legacy field: footer social items moved to Footer. For floating widget, use Floating Contact.
   */
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Frontend CTA fallback: used when a Pages block (e.g. Products Catalog / product cards) does not specify CTA copy.
   */
  ctaDefaults: {
    viewDetailsCta: string;
  };
  /**
   * Section titles used on the product detail page `/products/[slug]` (e.g. Applicable / Features / Sample Cases / Configuration).
   */
  productDetailLabels?: {
    applicable?: string | null;
    features?: string | null;
    sampleCases?: string | null;
    modules?: string | null;
    chassis?: string | null;
    arms?: string | null;
    composites?: string | null;
    configuration?: string | null;
    sensorConfig?: string | null;
    controllerConfig?: string | null;
    softwareConfig?: string | null;
    experiments?: string | null;
    specs?: string | null;
  };
  floatingContact?: {
    panelLabel?: string | null;
    fabLabel?: string | null;
    closeLabel?: string | null;
    qqGroup?: {
      label?: string | null;
      number?: string | null;
      tooltip?: string | null;
      copy?: string | null;
      copied?: string | null;
      qrImage?: (number | null) | Media;
    };
    wechat?: {
      label?: string | null;
      tooltip?: string | null;
      comingSoon?: string | null;
      qrImage?: (number | null) | Media;
    };
    phone?: {
      label?: string | null;
      name?: string | null;
      number?: string | null;
      tooltip?: string | null;
      copy?: string | null;
      copied?: string | null;
    };
    bilibili?: {
      label?: string | null;
      tooltip?: string | null;
      linkText?: string | null;
      href?: string | null;
    };
    taobao?: {
      label?: string | null;
      tooltip?: string | null;
      linkText?: string | null;
      href?: string | null;
    };
  };
  seoDefaults?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  cookieConsent?: {
    ariaLabel?: string | null;
    message?: string | null;
    /**
     * You can use a relative path like `/privacy-policy`; the frontend will resolve it for the active locale.
     */
    privacyPolicyLink?: string | null;
    learnMore?: string | null;
    acceptAll?: string | null;
    rejectNonEssential?: string | null;
  };
  /**
   * Displayed as the primary body on `/privacy-policy`; use it for privacy policy, cookie disclosure, and related legal text.
   */
  legalText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    href: string;
    children?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Used by the footer for phone / email / address (per locale).
   */
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  /**
   * Used by footer contact icons: Taobao/Bilibili are links; QQ/WeChat open QR modals.
   */
  contactItems?:
    | {
        key: 'taobao' | 'bilibili' | 'qq' | 'wechat';
        label: string;
        type: 'link' | 'qr';
        href?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy field: use Contact & Social Items instead.
   */
  qrCodes?:
    | {
        title: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  frontendBranding?:
    | T
    | {
        headerLogo?: T;
        headerLogoInverse?: T;
        footerLogo?: T;
        footerLogoInverse?: T;
        favicon?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaDefaults?:
    | T
    | {
        viewDetailsCta?: T;
      };
  productDetailLabels?:
    | T
    | {
        applicable?: T;
        features?: T;
        sampleCases?: T;
        modules?: T;
        chassis?: T;
        arms?: T;
        composites?: T;
        configuration?: T;
        sensorConfig?: T;
        controllerConfig?: T;
        softwareConfig?: T;
        experiments?: T;
        specs?: T;
      };
  floatingContact?:
    | T
    | {
        panelLabel?: T;
        fabLabel?: T;
        closeLabel?: T;
        qqGroup?:
          | T
          | {
              label?: T;
              number?: T;
              tooltip?: T;
              copy?: T;
              copied?: T;
              qrImage?: T;
            };
        wechat?:
          | T
          | {
              label?: T;
              tooltip?: T;
              comingSoon?: T;
              qrImage?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              name?: T;
              number?: T;
              tooltip?: T;
              copy?: T;
              copied?: T;
            };
        bilibili?:
          | T
          | {
              label?: T;
              tooltip?: T;
              linkText?: T;
              href?: T;
            };
        taobao?:
          | T
          | {
              label?: T;
              tooltip?: T;
              linkText?: T;
              href?: T;
            };
      };
  seoDefaults?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  cookieConsent?:
    | T
    | {
        ariaLabel?: T;
        message?: T;
        privacyPolicyLink?: T;
        learnMore?: T;
        acceptAll?: T;
        rejectNonEssential?: T;
      };
  legalText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  sections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  contactItems?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        href?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  qrCodes?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}